name: Lobby
version: '${project.version}'
main: com.abbas.lobby.Lobby
load: STARTUP
description: "Lobby Plugin"
authors:
  - Abbas
  - Aquix
api-version: 1.13
depend: [PlaceholderAPI, LuckPerms]

commands:
  # ICommandAPI Commands
  discord:
    usage: /<command>
  fly:
    usage: /<command>
  information:
    usage: /<command>
    aliases: [info]
  lobby:
    usage: /<command>
    aliases: [hub]
  ping:
    usage: /<command>
  spawn:
    usage: /<command>
  support:
    usage: /<command>
  vanish:
    usage: /<command>
  kick:
    usage: /<command>
  setspawn:
    usage: /<command>
  ban:
    usage: /<command>
  unban:
    usage: /<command>
  reloadconfig:
    usage: /<command>
  warn:
    usage: /<command>
  mute:
    usage: /<command>
  unmute:
    description: Unmute a player
    usage: /<command>
  sb:
    usage: /<command>
  togglevisibility:
    usage: /<command>
    aliases: [togglevis]
  dchat:
    description: Manage donator chat settings
    usage: /<command>
    aliases: [donatorchat]
  mutelist:
    description: Opens the mute list GUI
    usage: /<command>
    aliases: [mlist]
  nick:
    description: Change your display name
    usage: /<command> <nickname> or /<command> off
    aliases: [ nickname ]
permissions:
  # Admin Permissions
  lobby.ban:
    default: op
  lobby.kick:
    default: op
  lobby.mute:
    default: op
  lobby.reloadconfig:
    default: op
  lobby.setspawn:
    default: op
  lobby.unban:
    default: op
  lobby.unmute:
    default: op
  lobby.vanish:
    default: op
  lobby.warn:
    default: op
  lobby.mutelist:
    default: op
    # Donator Chat Permissions
  lobby.donatorchat:
    default: op
  lobby.donatorchat.toggle:
    default: op
  lobby.donatorchat.bypass.cooldown:
    default: op

    # Nickname Permissions
    lobby.command.nick:
      description: Allows a player to set or reset their own nickname
      default: true
    lobby.command.nick.color:
      description: Allows a player to use color codes in their nickname
      default: op
    lobby.command.nick.others:
      description: Allows an administrator to set or reset another player's nickname
      default: op

  # Premium Permissions
  lobby.fly:
    default: op
  lobby.fly.high:
    default: op
  # Player Permissions
  lobby.lobby:
    default: true
  lobby.information:
    default: true
  lobby.ping:
    default: true
  lobby.scoreboard:
    default: true
  lobby.support:
    default: true
  lobby.discord:
    default: true
  lobby.visibility.toggle:
    default: true
  # Event Permissions
  lobby.BlockPlace:
    default: op
  lobby.drop:
    default: op
  lobby.BlockBreak:
    default: op
