name: Lobby
version: '${project.version}'
main: com.abbas.lobby.Lobby
load: STARTUP
description: "Lobby Plugin"

commands:
  vanish:
    description: become invisible to normal players
  kick:
    desciption: kicks a player from the server
  help:
    description: Displays the Help Message
  ping:
    description: Displays the Players Ping
  Support:
    description: Displays the Support Message
  Discord:
    description:
  menu:
    description: Every
