name: Lobby
version: '${project.version}'
main: com.abbas.lobby.Lobby
load: STARTUP
description: "Lobby Plugin"
api-version: 1.13

commands:
  vanish:
    description: become invisible to normal players
  kick:
    desciption: kicks a player from the server
  help:
    description: Displays the Help Message
  ping:
    description: Displays the Players Ping
  Support:
    description: Displays the Support Message
  Discord:
    description:
  menu:
    description: Every
  lobby:
  SetSpawn:
    description: Sets the spawn point
    permission: lobby.setspawn
  Spawn:
    description: Teleports to the spawn point
    permission: lobby.spawn
  Ban:
  UnBan:
  reloadconfig:
  fly:
    description: Toggle fly mode
    usage: /fly [high]
    permission: lobby.fly
  permissions:
    lobby.fly:
      description: Allows the player to use /fly
      default: op
    lobby.fly.high:
      description: Allows the player to use high-speed flight mode (/fly high)
      default: op
